### PR TITLE
conainer improvement

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This improves container by adding:

- upgrade check skip
- fixing paths
- allowing to run any script set by RUNSCRIPT

### CODE REVIEW

**Comment by joshmoore** [comment]
Don't see any immediate issues. Couple of questions:

 * How best to test this without releasing a new tag?
 * Does this count as a breaking change? (I'd think likely so bump a larger number)
 * I'll restart re: "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself." but might be tough to get this green in the afternoon.

**Comment by aleksandra-tarkowska** [comment]
by running `./runtest` I release them in https://hub.docker.com/r/olat/omero-test-daemon-c7/

**Comment by aleksandra-tarkowska** [comment]
What is exactly breaking? especially that it hasn't been release?

**Comment by joshmoore** [comment]
> What is exactly breaking? especially that it hasn't been release?

The "API" of the container perhaps? Not sure. Still trying to figure out the best strategy for versioning images. Currently we're at https://github.com/openmicroscopy/omero-test-daemon-c7-docker/releases/tag/0.1.0

**Comment by aleksandra-tarkowska** [comment]
ok will do 0.2.0

**Comment by aleksandra-tarkowska** [comment]
I will ping you once I eventually have https://github.com/ome/omero-mapr/pull/4 using it

**Comment by aleksandra-tarkowska** [comment]
looks like it is timing out on `pip install zeroc-icepy` that is interesting

**Comment by aleksandra-tarkowska** [comment]
Looks like there are no problems in https://travis-ci.org/ome/omero-mapr/builds/180166243

**Comment by aleksandra-tarkowska** [comment]
@joshmoore good catch

```
maprtest_1     | build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
maprtest_1     |  #include <yaml.h>
```

propubly need libyaml-dev libpython2.7-dev or python-yaml

**Comment by joshmoore** [comment]
Merging in order to get https://github.com/ome/omero-mapr/pull/4 in. Travis may need to be looked into in a follow-on.

**Pull request merged**
